include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_const_constructors: true
    prefer_final_locals: true
    always_declare_return_types: true
    annotate_overrides: true
    avoid_print: true # Use logger ou debugPrint

