-- 1. Tabela de Projetos
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tech_stack text[] not null, -- Ex: ['Flutter', 'Dart']
  repo_url text not null,
  live_url text, -- Pode ser vazio
  image_url text, -- Link da imagem
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabela de Experiências
create table experiences (
  id bigint generated by default as identity primary key,
  role text not null, -- Cargo
  company text not null, -- Empresa
  period text not null, -- Período
  description text not null,
  is_current boolean default false, -- Se é o emprego atual
  start_date date, -- Útil para ordenar do mais recente para o antigo
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabela de Skills (Habilidades)
create table skills (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null, -- Vamos usar: 'mobile', 'web' ou 'tools'
  is_highlight boolean default false, -- Se é destaque (true/false)
  icon_asset text, -- Caminho do ícone (opcional)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- --- HABILITAR LEITURA PÚBLICA (ESSENCIAL) ---
-- Sem isso, seu site não consegue ler os dados

alter table projects enable row level security;
create policy "Qualquer um pode ler projetos" on projects for select using (true);

alter table experiences enable row level security;
create policy "Qualquer um pode ler experiencias" on experiences for select using (true);

alter table skills enable row level security;
create policy "Qualquer um pode ler skills" on skills for select using (true);

alter table certificates enable row level security;
create policy "Public Access" on certificates for select using (true);




-- Tabela PROJECTS
create policy "Admin Insert Projects" on projects for insert to authenticated with check (true);
create policy "Admin Update Projects" on projects for update to authenticated using (true);
create policy "Admin Delete Projects" on projects for delete to authenticated using (true);

-- Tabela EXPERIENCES
create policy "Admin Insert Exp" on experiences for insert to authenticated with check (true);
create policy "Admin Update Exp" on experiences for update to authenticated using (true);
create policy "Admin Delete Exp" on experiences for delete to authenticated using (true);

-- Tabela SKILLS
create policy "Admin Insert Skills" on skills for insert to authenticated with check (true);
create policy "Admin Update Skills" on skills for update to authenticated using (true);
create policy "Admin Delete Skills" on skills for delete to authenticated using (true);

-- Tabela CERTIFICATES
create policy "Admin Insert Certs" on certificates for insert to authenticated with check (true);
create policy "Admin Update Certs" on certificates for update to authenticated using (true);
create policy "Admin Delete Certs" on certificates for delete to authenticated using (true);


create table app_logs (
  id bigserial primary key,
  level text,         -- info, debug, error, warning
  message text,
  stack text,
  timestamp timestamptz default now(),
  user_id uuid        -- opcional, se tiver login
);

-- Habilitar RLS
alter table app_logs enable row level security;

-- Permitir inserção de logs (autenticados ou anônimos)
create policy "Qualquer um pode inserir logs"
on app_logs
for insert
with check (true);

-- Permitir que o usuário selecione apenas seus próprios logs
create policy "Usuário pode ler seus próprios logs"
on app_logs
for select
using (auth.uid() = user_id);

-- Permitir que admins leiam todos os logs
create policy "Admin pode ler todos os logs"
on app_logs
for select
using (auth.uid() IN (
  -- Adicione aqui os UUIDs dos usuários admin
  -- Exemplo: 'uuid-do-admin-1', 'uuid-do-admin-2'
  select id from auth.users where email = 'seu-email-admin@exemplo.com'
));


