-- 1. Tabela de Projetos
create table projects (
  id bigint generated by default as identity primary key,
  title text not null,
  description text not null,
  tech_stack text[] not null, -- Ex: ['Flutter', 'Dart']
  repo_url text not null,
  live_url text, -- Pode ser vazio
  image_url text, -- Link da imagem
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabela de Experiências
create table experiences (
  id bigint generated by default as identity primary key,
  role text not null, -- Cargo
  company text not null, -- Empresa
  period text not null, -- Período
  description text not null,
  is_current boolean default false, -- Se é o emprego atual
  start_date date, -- Útil para ordenar do mais recente para o antigo
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Tabela de Skills (Habilidades)
create table skills (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null, -- Vamos usar: 'mobile', 'web' ou 'tools'
  is_highlight boolean default false, -- Se é destaque (true/false)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- --- HABILITAR LEITURA PÚBLICA (ESSENCIAL) ---
-- Sem isso, seu site não consegue ler os dados

alter table projects enable row level security;
create policy "Qualquer um pode ler projetos" on projects for select using (true);

alter table experiences enable row level security;
create policy "Qualquer um pode ler experiencias" on experiences for select using (true);

alter table skills enable row level security;
create policy "Qualquer um pode ler skills" on skills for select using (true);